### ISSUE TITLE
scribo/content_in_doc: not found

### ISSUE THREAD

**Issue by andrewluetgers** [glazzara/olena#1]
I'm trying to run the document image analysis to get segmentation information but the scribo-cli doc-dia command fails. I have tried building both on mac and ubuntu with the same results.

root@c517f00ea21b:/olena-2.1# scribo-cli doc-dia
/usr/local/bin/scribo-cli: 115: /usr/local/bin/scribo-cli: /usr/local/libexec/scribo/content_in_doc: not found

**Comment by andrewluetgers** [comment]
@roland-levillain could you please comment on this?

**Comment by roland-levillain** [comment]
I am no longer working on the Olena project. Please contact the Olena team at olena@lrde.epita.fr.

**Comment by andrewluetgers** [comment]
Sorry, the problem was that I did not install the QT UI dependencies assuming i did not need to If I was not going to use the UI.
